apiVersion: v1
kind: Namespace
metadata:
  name: hitl
  labels:
    app.kubernetes.io/part-of: hitl-runtime
    app.kubernetes.io/managed-by: kubectl
    addepar.dev/env: dev
    addepar.dev/cluster: hitl-runtime
